### ISSUE TITLE
Support Windows

### ISSUE THREAD

**Issue by ChangJoo-Park** [Parabeac/Parabeac-Core#29]
I tried Parabeac with my windows machine. it failed [this line](https://github.com/Parabeac/Parabeac-Core/blob/b4f31ef858d0f10a6e489b9fbb63cae1a0adcde8/parabeac.dart#L34)

- Using batch file for windows. all scripts inside pb-scripts are for *nix System.

`install.sh`

```
echo "[INFO]: Installing Para-beac core and its dependencies"
dart pub get
cd SketchAssetConverter && npm i
echo "Installed Sketch Asset Converter dependencies"
```

to 

`install.bat`

```
@echo off

echo "[INFO]: Installing Para-beac core and its dependencies"
pub get
cd SketchAssetConverter
npm i
echo "Installed Sketch Asset Converter dependencies"
```

Error message here.

```
➜ dart .\parabeac.dart -p C:\Users\development\Parabeac-Core\parabeac_demo_alt.sketch -n C:\Users\development\parabeac-flutter
Unhandled exception:
FormatException: Unexpected extension byte (at offset 10)
#0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1887:7)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:28)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
#5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#8      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#9      _StreamController._add (dart:async/stream_controller.dart:682:7)
#10     _StreamController.add (dart:async/stream_controller.dart:624:5)
#11     _Socket._onData (dart:io-patch/socket_patch.dart:2020:41)
#12     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#15     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#16     _StreamController._add (dart:async/stream_controller.dart:682:7)
#17     _StreamController.add (dart:async/stream_controller.dart:624:5)
#18     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1556:33)
#19     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1052:14)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

**Comment by siliconivan** [comment]
I believe we can revisit this when we have support for Figma, since we rely on the Sketch-tool library that's only available on Mac, we can't produce images on Windows from Sketch. Although, I'm curious if we should even support Sketch on Windows if you can't use Sketch on Windows. Maybe the default should be Figma for Windows.

**Comment by ChangJoo-Park** [comment]
I think if working Parabeac on mac well, support windows have no problem.  At this time we focus on Parabeac-Core on *nix system.

**Comment by snwagbata** [comment]
I was able to get the sh files to run after a few modifications to `parabeac.dart`  and using bash. However, it seems like Process does not recognize the sketch file
```
$ dart lib/main.dart -p "c:/users/cn/desktop/parabeac_demo_alt.sketch" -n f
lib/main.dart: Warning: Interpreting this as package URI, 'package:parabeac_core/main.dart'.
Main: [INFO] - [-p, c:/users/cn/desktop/parabeac_demo_alt.sketch, -n, f]
CreateProcessW failed 2
Unhandled exception:
ProcessException: The system cannot find the file specified.

  Command: npm run prod
```

**Comment by siliconivan** [comment]
PBC supports windows with Figma now, you can watch a video here: https://www.youtube.com/watch?v=Pr52-9Ni4Ds
